# Generated by Django 5.0.2 on 2024-02-22 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jam', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendedsongs',
            name='library',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='users.library'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recommendedsongs',
            name='like',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='jam.like'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recommendedsongs',
            name='profile',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recommendedsongs',
            name='similarreleases',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='jam.similarreleases'),
            preserve_default=False,
        ),
    ]
