# Generated by Django 5.0.2 on 2024-02-24 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jam', '0002_recommendedsongs_library_recommendedsongs_like_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
    ]
