# Generated by Django 5.0.2 on 2024-02-28 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jam', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favourites',
            name='content_type',
        ),
    ]
