# Generated by Django 5.0.2 on 2024-02-24 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jam', '0003_remove_like_content_type_remove_like_user'),
        ('users', '0002_alter_library_created_playlists_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendedsongs',
            name='like',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.like'),
        ),
        migrations.AlterField(
            model_name='feeds',
            name='likes',
            field=models.ManyToManyField(to='users.like'),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
