# Generated by Django 5.0.2 on 2024-02-28 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jam', '0003_remove_favourites_content_type'),
        ('users', '0002_favourites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommended',
            name='favourite',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.favourites'),
        ),
        migrations.DeleteModel(
            name='Favourites',
        ),
    ]
