# Generated by Django 5.0 on 2023-12-26 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('music', '0002_remove_playlist_songs_remove_playlist_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_playlists', models.ManyToManyField(blank=True, related_name='users_created_playlists', to='music.playlist')),
                ('favorite_artists', models.ManyToManyField(related_name='users_favorite_artists', to='music.artist')),
                ('saved_albums', models.ManyToManyField(related_name='users_saved_albums', to='music.album')),
                ('saved_songs', models.ManyToManyField(related_name='users_saved_songs', to='music.song')),
                ('uploaded_songs', models.ManyToManyField(blank=True, related_name='users_uploaded_songs', to='music.song')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='users_user_library', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('bio', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='users_user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
