# Generated by Django 5.0.2 on 2024-02-21 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('music', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_playlists', models.ManyToManyField(blank=True, related_name='created_in_libraries', to='music.playlist')),
                ('favorite_artists', models.ManyToManyField(blank=True, related_name='favorited_in_libraries', to='music.artist')),
                ('saved_albums', models.ManyToManyField(blank=True, related_name='saved_in_libraries', to='music.album')),
                ('saved_playlists', models.ManyToManyField(blank=True, related_name='saved_in_libraries', to='music.playlist')),
                ('saved_songs', models.ManyToManyField(blank=True, related_name='saved_in_libraries', to='music.song')),
            ],
            options={
                'db_table': 'profile_user_library',
            },
        ),
        migrations.CreateModel(
            name='ListeningHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listened_at', models.DateTimeField(auto_now_add=True)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.song')),
                ('user_library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.library')),
            ],
            options={
                'db_table': 'profile_listening_history',
            },
        ),
        migrations.AddField(
            model_name='library',
            name='recently_played',
            field=models.ManyToManyField(blank=True, related_name='played_by_users', through='users.ListeningHistory', to='music.song'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('bio', models.TextField(blank=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('last_viewed', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profile_user_profile',
            },
        ),
        migrations.AddField(
            model_name='listeninghistory',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
        migrations.AddField(
            model_name='library',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='library', to='users.profile'),
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', help_text='Choose app theme', max_length=20)),
                ('notifications_enabled', models.BooleanField(default=True, help_text='Enable notifications')),
                ('auto_play_enabled', models.BooleanField(default=False, help_text='Enable auto-play feature')),
                ('repeat_mode', models.CharField(choices=[('none', 'None'), ('all', 'All'), ('one', 'One')], default='none', help_text='Set repeat mode', max_length=20)),
                ('language', models.CharField(default='en', help_text='Choose app language', max_length=20)),
                ('download_quality', models.CharField(choices=[('standard', 'Standard'), ('high', 'High'), ('lossless', 'Lossless')], default='standard', help_text='Set download quality', max_length=20)),
                ('streaming_quality', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', help_text='Set streaming quality', max_length=20)),
                ('equalizer_enabled', models.BooleanField(default=False, help_text='Enable equalizer')),
                ('local_files_access', models.BooleanField(default=False, help_text='Enable access to local files')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
