# Generated by Django 5.0 on 2024-01-08 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_playlist_cover_image'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table=None,
        ),
        migrations.CreateModel(
            name='ListeningHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listened_at', models.DateTimeField(auto_now_add=True)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.song')),
                ('user_library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userlibrary')),
            ],
            options={
                'db_table': 'profile_listening_history',
            },
        ),
        migrations.AddField(
            model_name='userlibrary',
            name='recently_played',
            field=models.ManyToManyField(blank=True, related_name='played_by_users', through='users.ListeningHistory', to='music.song'),
        ),
    ]
