# Generated by Django 5.0 on 2023-12-27 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_album_rating_song_rating'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlibrary',
            name='created_playlists',
        ),
        migrations.RemoveField(
            model_name='userlibrary',
            name='uploaded_songs',
        ),
        migrations.RemoveField(
            model_name='userlibrary',
            name='user',
        ),
        migrations.AddField(
            model_name='userlibrary',
            name='user_profile',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='library', to='users.userprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created_playlists',
            field=models.ManyToManyField(blank=True, related_name='users_created_playlists', to='music.playlist'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='favorite_artists',
            field=models.ManyToManyField(blank=True, related_name='users_favorite_artists', to='music.artist'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='saved_albums',
            field=models.ManyToManyField(blank=True, related_name='users_saved_albums', to='music.album'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='saved_songs',
            field=models.ManyToManyField(blank=True, related_name='users_saved_songs', to='music.song'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='uploaded_songs',
            field=models.ManyToManyField(blank=True, related_name='users_uploaded_songs', to='music.song'),
        ),
        migrations.AlterField(
            model_name='userlibrary',
            name='favorite_artists',
            field=models.ManyToManyField(blank=True, related_name='user_library_favorite_artists', to='music.artist'),
        ),
        migrations.AlterField(
            model_name='userlibrary',
            name='saved_albums',
            field=models.ManyToManyField(blank=True, related_name='user_library_saved_albums', to='music.album'),
        ),
        migrations.AlterField(
            model_name='userlibrary',
            name='saved_songs',
            field=models.ManyToManyField(blank=True, related_name='user_library_saved_songs', to='music.song'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
