# Generated by Django 5.0.2 on 2024-02-24 03:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('music', '0003_remove_userprofile_user_genreradio_and_more'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='created_playlists',
            field=models.ManyToManyField(blank=True, related_name='created_in_library', to='music.playlist'),
        ),
        migrations.AlterField(
            model_name='library',
            name='favorite_artists',
            field=models.ManyToManyField(blank=True, related_name='favorite_in_library', to='music.artist'),
        ),
        migrations.AlterField(
            model_name='library',
            name='saved_albums',
            field=models.ManyToManyField(blank=True, related_name='saved_in_library', to='music.album'),
        ),
        migrations.AlterField(
            model_name='library',
            name='saved_playlists',
            field=models.ManyToManyField(blank=True, related_name='saved_in_library', to='music.playlist'),
        ),
        migrations.AlterField(
            model_name='library',
            name='saved_songs',
            field=models.ManyToManyField(blank=True, related_name='saved_in_library', to='music.song'),
        ),
        migrations.AlterModelTable(
            name='profile',
            table=None,
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
