# Generated by Django 5.0 on 2024-01-11 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_playlist_cover_image'),
        ('users', '0002_alter_userprofile_user_alter_userprofile_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listeninghistory',
            name='user_profile',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='users.userprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created_playlists',
            field=models.ManyToManyField(blank=True, related_name='created_in_user_profiles', to='music.playlist'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='favorite_artists',
            field=models.ManyToManyField(blank=True, related_name='favorited_in_user_profiles', to='music.artist'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_viewed',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='recently_played',
            field=models.ManyToManyField(blank=True, related_name='played_by_user_profiles', through='users.ListeningHistory', to='music.song'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='saved_albums',
            field=models.ManyToManyField(blank=True, related_name='saved_in_user_profiles', to='music.album'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='saved_songs',
            field=models.ManyToManyField(blank=True, related_name='saved_in_user_profiles', to='music.song'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='profile_user_profile',
        ),
        migrations.DeleteModel(
            name='UserProfileView',
        ),
    ]
