# Generated by Django 5.0.2 on 2024-03-03 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
        ('users', '0002_favourites'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favourite_genres',
            field=models.ManyToManyField(to='music.genre'),
        ),
    ]
