# Generated by Django 5.0 on 2023-12-27 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_album_rating_song_rating'),
        ('users', '0003_userprofileview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='created_playlists',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='favorite_artists',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='saved_albums',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='saved_songs',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='uploaded_songs',
        ),
        migrations.RemoveField(
            model_name='userprofileview',
            name='user',
        ),
        migrations.AddField(
            model_name='userlibrary',
            name='created_playlists',
            field=models.ManyToManyField(blank=True, related_name='user_library_created_playlists', to='music.playlist'),
        ),
        migrations.AddField(
            model_name='userprofileview',
            name='user_profile',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='profile_views', to='users.userprofile'),
            preserve_default=False,
        ),
    ]
