# Generated by Django 5.0 on 2023-12-27 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_album_rating_song_rating'),
        ('users', '0004_remove_userprofile_created_playlists_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlibrary',
            name='created_playlists',
            field=models.ManyToManyField(blank=True, related_name='profile_created_playlists', to='music.playlist'),
        ),
        migrations.AlterField(
            model_name='userlibrary',
            name='favorite_artists',
            field=models.ManyToManyField(blank=True, related_name='profile_favorite_artists', to='music.artist'),
        ),
        migrations.AlterField(
            model_name='userlibrary',
            name='saved_albums',
            field=models.ManyToManyField(blank=True, related_name='profile_saved_albums', to='music.album'),
        ),
        migrations.AlterField(
            model_name='userlibrary',
            name='saved_songs',
            field=models.ManyToManyField(blank=True, related_name='profile_saved_songs', to='music.song'),
        ),
        migrations.AlterField(
            model_name='userlibrary',
            name='user_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_library', to='users.userprofile'),
        ),
        migrations.AlterField(
            model_name='userprofileview',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_profile_views', to='users.userprofile'),
        ),
        migrations.AlterModelTable(
            name='userlibrary',
            table='profile_user_library',
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='profile_user_profile',
        ),
        migrations.AlterModelTable(
            name='userprofileview',
            table='profile_user_profile_view',
        ),
    ]
