# Generated by Django 5.0.2 on 2024-03-06 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='artist_covers/')),
                ('bio', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(choices=[('Pop', 'Pop'), ('Hip-hop/Rap', 'Hip-hop/Rap'), ('R&B/Soul', 'R&B/Soul'), ('Rock', 'Rock'), ('Country', 'Country'), ('Electronic/Dance', 'Electronic/Dance'), ('Reggaeton', 'Reggaeton'), ('Jazz', 'Jazz'), ('Indie/Alternative', 'Indie/Alternative'), ('Latin', 'Latin'), ('Afrobeat', 'Afrobeat'), ('Highlife', 'Highlife'), ('Afrobeats', 'Afrobeats'), ('Soukous', 'Soukous'), ('Afro-house', 'Afro-house'), ('Mbalax', 'Mbalax'), ('Juju', 'Juju'), ('Rai', 'Rai'), ('Kizomba', 'Kizomba'), ('Gqom', 'Gqom'), ('Bollywood', 'Bollywood'), ('K-pop', 'K-pop'), ('J-pop', 'J-pop'), ('C-pop', 'C-pop'), ('Traditional_Asian', 'Traditional Asian'), ('Classical', 'Classical'), ('Folk', 'Folk'), ('Reggae', 'Reggae'), ('Metal', 'Metal'), ('Samba', 'Samba'), ('Cumbia', 'Cumbia'), ('Bossa_Nova', 'Bossa Nova'), ('Tango', 'Tango'), ('Andean_music', 'Andean music'), ('Zamba', 'Zamba'), ('Axé', 'Axé'), ('Forró', 'Forró'), ('Indigenous', 'Indigenous')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('cover_image', models.ImageField(upload_to='album_covers/')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.artist')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.genre')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='song_covers/')),
                ('audio_file', models.FileField(upload_to='songs/')),
                ('is_single', models.BooleanField(default=True)),
                ('composer', models.CharField(blank=True, max_length=100, null=True)),
                ('producer', models.CharField(blank=True, max_length=100, null=True)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='music.album')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.artist')),
                ('feature', models.ManyToManyField(blank=True, related_name='featured', to='music.artist')),
                ('genre', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='music.genre')),
            ],
            options={
                'unique_together': {('title', 'artist')},
            },
        ),
        migrations.AddField(
            model_name='album',
            name='songs',
            field=models.ManyToManyField(blank=True, related_name='albums', to='music.song'),
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('cover_image', models.ImageField(upload_to='playlist_covers/')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.artist')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.genre')),
                ('songs', models.ManyToManyField(to='music.song')),
            ],
            options={
                'unique_together': {('title',)},
            },
        ),
        migrations.AlterUniqueTogether(
            name='album',
            unique_together={('title', 'artist')},
        ),
    ]
