# Generated by Django 5.0 on 2023-12-26 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='songs',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='user',
        ),
        migrations.AddField(
            model_name='album',
            name='cover_image',
            field=models.ImageField(default=0, upload_to='album_covers/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playlist',
            name='song',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='music.song'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userlibrary',
            name='created_playlists',
            field=models.ManyToManyField(blank=True, related_name='music_created_playlists', to='music.playlist'),
        ),
        migrations.AlterField(
            model_name='userlibrary',
            name='favorite_artists',
            field=models.ManyToManyField(related_name='music_favorite_artists', to='music.artist'),
        ),
        migrations.AlterField(
            model_name='userlibrary',
            name='saved_albums',
            field=models.ManyToManyField(related_name='music_saved_albums', to='music.album'),
        ),
        migrations.AlterField(
            model_name='userlibrary',
            name='saved_songs',
            field=models.ManyToManyField(related_name='music_saved_songs', to='music.song'),
        ),
        migrations.AlterField(
            model_name='userlibrary',
            name='uploaded_songs',
            field=models.ManyToManyField(blank=True, related_name='music_uploaded_songs', to='music.song'),
        ),
        migrations.AlterField(
            model_name='userlibrary',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='music_user_library', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='music_user_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.song')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='UserPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('songs', models.ManyToManyField(to='music.song')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.userprofile')),
            ],
        ),
    ]
