# Generated by Django 5.0.2 on 2024-03-09 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='album',
        ),
        migrations.RemoveField(
            model_name='song',
            name='composer',
        ),
        migrations.RemoveField(
            model_name='song',
            name='is_single',
        ),
        migrations.RemoveField(
            model_name='song',
            name='producer',
        ),
        migrations.RemoveField(
            model_name='song',
            name='feature',
        ),
        migrations.AddField(
            model_name='song',
            name='feature',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='featured', to='music.artist'),
            preserve_default=False,
        ),
    ]
