# Generated by Django 5.0.2 on 2024-03-03 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_remove_album_mood_remove_playlist_mood_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artistradio',
            name='mood',
        ),
        migrations.RemoveField(
            model_name='genreradio',
            name='mood',
        ),
        migrations.DeleteModel(
            name='Mood',
        ),
    ]
