# Generated by Django 5.0 on 2023-12-26 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_song_artist_song_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='title',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='title',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='userplaylist',
            name='title',
            field=models.TextField(max_length=200),
        ),
    ]
