# Generated by Django 5.0.2 on 2024-03-04 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_remove_artistradio_mood_remove_genreradio_mood_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genreradio',
            name='genre',
        ),
        migrations.DeleteModel(
            name='ArtistRadio',
        ),
        migrations.DeleteModel(
            name='GenreRadio',
        ),
    ]
