# Generated by Django 5.0 on 2023-12-26 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_alter_album_title_alter_artist_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='file_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
