# Generated by Django 5.0 on 2024-01-08 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_alter_audiofile_audio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='cover_image',
            field=models.ImageField(default=0, upload_to='playlist_covers/'),
            preserve_default=False,
        ),
    ]
