# Generated by Django 5.0 on 2024-02-08 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_playlist_genre_alter_album_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='composer',
            name='name',
        ),
        migrations.AddField(
            model_name='composer',
            name='artist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='music.artist'),
            preserve_default=False,
        ),
    ]
