# Generated by Django 5.0 on 2023-12-27 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_alter_userlibrary_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='rating',
            field=models.CharField(choices=[('Good', 'Good'), ('Okay', 'Okay'), ('Mid', 'Mid'), ('Bad', 'Bad')], default='Okay', max_length=10),
        ),
        migrations.AddField(
            model_name='song',
            name='rating',
            field=models.CharField(choices=[('Good', 'Good'), ('Okay', 'Okay'), ('Mid', 'Mid'), ('Bad', 'Bad')], default='Okay', max_length=10),
        ),
    ]
