# Generated by Django 5.0 on 2023-12-28 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_album_rating_song_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='song',
        ),
        migrations.AddField(
            model_name='playlist',
            name='songs',
            field=models.ManyToManyField(to='music.song'),
        ),
        migrations.AlterField(
            model_name='userlibrary',
            name='created_playlists',
            field=models.ManyToManyField(blank=True, related_name='music_created_in_libraries', to='music.playlist'),
        ),
        migrations.AlterField(
            model_name='userlibrary',
            name='favorite_artists',
            field=models.ManyToManyField(related_name='music_favorited_in_libraries', to='music.artist'),
        ),
        migrations.AlterField(
            model_name='userlibrary',
            name='saved_albums',
            field=models.ManyToManyField(related_name='music_saved_in_libraries', to='music.album'),
        ),
        migrations.AlterField(
            model_name='userlibrary',
            name='saved_songs',
            field=models.ManyToManyField(related_name='music_saved_in_libraries', to='music.song'),
        ),
    ]
