# Generated by Django 5.0 on 2024-02-08 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_alter_artist_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='composer',
            name='artist',
        ),
        migrations.AddField(
            model_name='composer',
            name='name',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
