# Generated by Django 5.0 on 2024-02-08 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_remove_composer_artist_composer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='feature',
            field=models.ManyToManyField(blank=True, related_name='featured_in', to='music.artist'),
        ),
    ]
