# Generated by Django 5.0 on 2023-12-29 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_remove_playlist_song_playlist_songs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userplaylist',
            name='songs',
        ),
        migrations.RemoveField(
            model_name='userplaylist',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userlibrary',
            name='user',
        ),
        migrations.AddField(
            model_name='userlibrary',
            name='user_profile',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='music_user_library', to='music.userprofile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.DeleteModel(
            name='UserFavorite',
        ),
        migrations.DeleteModel(
            name='UserPlaylist',
        ),
    ]
