# Generated by Django 5.0 on 2024-02-09 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0012_song_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='feature_2',
            field=models.ManyToManyField(blank=True, related_name='featured_in', to='music.artist'),
        ),
        migrations.AlterField(
            model_name='song',
            name='feature',
            field=models.ManyToManyField(blank=True, related_name='featured', to='music.artist'),
        ),
    ]
