# Generated by Django 5.0 on 2024-02-10 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0013_song_feature_2_alter_song_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='artist_covers/'),
        ),
    ]
