# Generated by Django 5.0 on 2024-02-13 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0014_artist_bio_artist_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='composer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='song',
            name='feature_2',
        ),
        migrations.DeleteModel(
            name='Composer',
        ),
    ]
