# Generated by Django 5.0 on 2024-02-13 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0015_alter_song_composer_remove_song_feature_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='producer',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
