# Generated by Django 5.0.2 on 2024-02-22 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Music',
        ),
    ]
