# Generated by Django 5.0.2 on 2024-02-24 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0002_delete_music'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('artist', models.CharField(max_length=200)),
                ('album', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('audio_file', models.FileField(upload_to='audio/')),
                ('copyright_status', models.CharField(max_length=50)),
            ],
        ),
    ]
