# Generated by Django 5.0 on 2024-02-07 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='radiostation',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='radiostation',
            name='genre',
        ),
    ]
