# Generated by Django 5.0 on 2024-02-07 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0002_remove_radiostation_frequency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='radiostation',
            name='city',
        ),
        migrations.RemoveField(
            model_name='radiostation',
            name='country',
        ),
        migrations.RemoveField(
            model_name='radiostation',
            name='stream_url',
        ),
    ]
