# Generated by Django 5.0 on 2023-12-31 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='audio_file',
            field=models.FileField(default=0, upload_to='songs/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='song_covers/'),
        ),
        migrations.AddField(
            model_name='song',
            name='is_single',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.album'),
        ),
    ]
