# Generated by Django 5.0 on 2023-12-30 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='songs',
            field=models.ManyToManyField(blank=True, related_name='albums', to='catalog.song'),
        ),
        migrations.AddField(
            model_name='song',
            name='artist',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='catalog.artist'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='is_single',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
