# Generated by Django 5.0 on 2023-12-31 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_song_audio_file_song_cover_image_song_is_single_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='composer',
        ),
        migrations.DeleteModel(
            name='Composer',
        ),
    ]
