# Generated by Django 5.0.2 on 2024-02-28 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_album_genre_alter_song_genre_delete_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='ft_artist',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
