# Generated by Django 5.0 on 2024-01-01 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_composer_song_composer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='composer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.composer'),
        ),
    ]
